grpc:
  server:
    enabled: false # ??????? GRPC ?? ????
  client:
    exchange-server:
      address: static://localhost:9090 # GRPC ?? ?? ? ??
      negotiation-type: plaintext      # ?? ?? ?? ?? (Plaintext)
      keep-alive-time: 60s             # KeepAlive ?? (60?)
      keep-alive-timeout: 20s          # KeepAlive ???? (20?)
      keep-alive-without-calls: true   # ??? ??? KeepAlive ??

spring:
  application:
    name: exchange-client # ????? ?????? ??

logging:
  level:
    root: INFO
    com.java.exchangeclient: DEBUG